import 'package:flutter/material.dart';
import 'package:moneii_manager/config/theme.dart';

class CategoryData {
  final String name;
  final IconData icon;
  final Color color;
  final List<String> subcategories;
  final List<String> keywords;

  const CategoryData({
    required this.name,
    required this.icon,
    required this.color,
    required this.subcategories,
    required this.keywords,
  });
}

class AppCategories {
  static const List<CategoryData> all = [
    CategoryData(
      name: 'Food & Dining',
      icon: Icons.restaurant_rounded,
      color: AppColors.categoryFood,
      subcategories: [
        'Groceries',
        'Restaurants',
        'Coffee & Tea',
        'Fast Food',
        'Desserts',
        'Alcohol & Bars',
        'Meal Delivery',
      ],
      keywords: [
        'lunch',
        'dinner',
        'breakfast',
        'coffee',
        'food',
        'eat',
        'restaurant',
        'pizza',
        'burger',
        'snack',
        'grocery',
        'groceries',
        'meal',
        'brunch',
        'sushi',
        'takeout',
        'delivery',
        'dessert',
        'cake',
        'tea',
        'bar',
        'drinks',
        'beer',
        'wine',
        'alcohol',
        'starbucks',
        'mcdonalds',
        'kfc',
        'subway',
        'chipotle',
      ],
    ),
    CategoryData(
      name: 'Transport',
      icon: Icons.directions_car_rounded,
      color: AppColors.categoryTransport,
      subcategories: [
        'Fuel/Gas',
        'Public Transit',
        'Ride Share',
        'Parking',
        'Car Maintenance',
        'Flights',
      ],
      keywords: [
        'uber',
        'lyft',
        'taxi',
        'cab',
        'bus',
        'train',
        'subway',
        'metro',
        'gas',
        'fuel',
        'parking',
        'toll',
        'ride',
        'commute',
        'flight',
        'airline',
        'car',
        'maintenance',
        'oil change',
        'tire',
        'transit',
      ],
    ),
    CategoryData(
      name: 'Entertainment',
      icon: Icons.movie_rounded,
      color: AppColors.categoryEntertainment,
      subcategories: [
        'Movies & TV',
        'Music & Concerts',
        'Gaming',
        'Sports',
        'Nightlife',
        'Streaming Subscriptions',
      ],
      keywords: [
        'movie',
        'movies',
        'cinema',
        'netflix',
        'spotify',
        'game',
        'gaming',
        'concert',
        'show',
        'theater',
        'nightclub',
        'club',
        'party',
        'hulu',
        'disney',
        'youtube',
        'twitch',
        'steam',
        'playstation',
        'xbox',
        'nintendo',
        'sports',
        'ticket',
      ],
    ),
    CategoryData(
      name: 'Shopping',
      icon: Icons.shopping_bag_rounded,
      color: AppColors.categoryShopping,
      subcategories: [
        'Clothing & Fashion',
        'Electronics',
        'Home & Decor',
        'Beauty & Personal Care',
        'Gifts',
        'Online Shopping',
      ],
      keywords: [
        'clothes',
        'shoes',
        'amazon',
        'online',
        'store',
        'mall',
        'shirt',
        'pants',
        'jacket',
        'dress',
        'electronics',
        'phone',
        'laptop',
        'headphones',
        'beauty',
        'makeup',
        'skincare',
        'gift',
        'present',
        'decor',
        'furniture',
        'target',
        'walmart',
        'zara',
        'nike',
        'adidas',
      ],
    ),
    CategoryData(
      name: 'Bills & Utilities',
      icon: Icons.receipt_long_rounded,
      color: AppColors.categoryBills,
      subcategories: [
        'Rent/Mortgage',
        'Electricity',
        'Water',
        'Internet & WiFi',
        'Phone',
        'Insurance',
        'Subscriptions',
      ],
      keywords: [
        'rent',
        'mortgage',
        'electric',
        'electricity',
        'water',
        'internet',
        'wifi',
        'phone',
        'bill',
        'insurance',
        'subscription',
        'utility',
        'utilities',
        'cable',
        'gas bill',
      ],
    ),
    CategoryData(
      name: 'Health & Fitness',
      icon: Icons.favorite_rounded,
      color: AppColors.categoryHealth,
      subcategories: [
        'Gym & Fitness',
        'Doctor & Hospital',
        'Pharmacy/Medicine',
        'Mental Health',
        'Supplements',
      ],
      keywords: [
        'doctor',
        'hospital',
        'medicine',
        'pharmacy',
        'gym',
        'workout',
        'dentist',
        'therapy',
        'health',
        'medical',
        'prescription',
        'vitamin',
        'supplement',
        'fitness',
        'yoga',
        'pilates',
      ],
    ),
    CategoryData(
      name: 'Education',
      icon: Icons.school_rounded,
      color: AppColors.categoryEducation,
      subcategories: [
        'Books',
        'Courses & Online Learning',
        'Tuition',
        'Stationery',
        'Software & Tools',
      ],
      keywords: [
        'book',
        'books',
        'course',
        'class',
        'tuition',
        'school',
        'university',
        'udemy',
        'coursera',
        'study',
        'education',
        'learning',
        'stationery',
        'textbook',
      ],
    ),
    CategoryData(
      name: 'Travel',
      icon: Icons.flight_rounded,
      color: AppColors.categoryTravel,
      subcategories: [
        'Hotels',
        'Flights',
        'Activities',
        'Travel Food',
        'Travel Shopping',
      ],
      keywords: [
        'hotel',
        'airbnb',
        'travel',
        'trip',
        'vacation',
        'resort',
        'hostel',
        'booking',
        'tour',
        'sightseeing',
        'adventure',
      ],
    ),
    CategoryData(
      name: 'Personal',
      icon: Icons.person_rounded,
      color: AppColors.categoryPersonal,
      subcategories: [
        'Haircut & Grooming',
        'Laundry',
        'Donations & Charity',
        'Pets',
      ],
      keywords: [
        'haircut',
        'grooming',
        'salon',
        'barber',
        'laundry',
        'dry clean',
        'donation',
        'charity',
        'pet',
        'dog',
        'cat',
        'vet',
        'veterinary',
      ],
    ),
    CategoryData(
      name: 'Income',
      icon: Icons.account_balance_wallet_rounded,
      color: AppColors.categoryIncome,
      subcategories: [
        'Salary',
        'Freelance',
        'Investments',
        'Refunds',
        'Gifts Received',
      ],
      keywords: [
        'salary',
        'paycheck',
        'freelance',
        'income',
        'investment',
        'dividend',
        'refund',
        'bonus',
        'commission',
        'tip',
        'received',
        'earned',
      ],
    ),
    CategoryData(
      name: 'Other',
      icon: Icons.more_horiz_rounded,
      color: AppColors.categoryOther,
      subcategories: ['Miscellaneous', 'ATM Withdrawal', 'Fees & Charges'],
      keywords: ['atm', 'withdrawal', 'fee', 'charge', 'misc', 'other'],
    ),
  ];

  static CategoryData getByName(String name) {
    return all.firstWhere((c) => c.name == name, orElse: () => all.last);
  }
}

class AppConstants {
  static const String appName = 'MoneiiManager';
  static const String defaultCurrency = 'USD';
  static const int maxRecordingDurationSeconds = 30;
  static const String whisperModel = 'whisper-1';
  static const String whisperApiUrl =
      'https://api.openai.com/v1/audio/transcriptions';
}
