create table if not exists public.ai_assistant_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  prompt text not null,
  response text,
  status text not null default 'started',
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists ai_assistant_requests_user_created_idx
  on public.ai_assistant_requests(user_id, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ai_assistant_requests_status_check'
  ) then
    alter table public.ai_assistant_requests
      add constraint ai_assistant_requests_status_check
      check (status in ('started', 'success', 'failed'));
  end if;
end
$$;

alter table public.ai_assistant_requests enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_assistant_requests'
      and policyname = 'ai_assistant_requests_select_own'
  ) then
    create policy "ai_assistant_requests_select_own"
      on public.ai_assistant_requests for select
      using (auth.uid() = user_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_assistant_requests'
      and policyname = 'ai_assistant_requests_insert_own'
  ) then
    create policy "ai_assistant_requests_insert_own"
      on public.ai_assistant_requests for insert
      with check (auth.uid() = user_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_assistant_requests'
      and policyname = 'ai_assistant_requests_update_own'
  ) then
    create policy "ai_assistant_requests_update_own"
      on public.ai_assistant_requests for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end
$$;
