create table if not exists public.voice_entry_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expense_id uuid,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists voice_entry_ledger_user_created_idx
  on public.voice_entry_ledger(user_id, created_at desc);

alter table public.voice_entry_ledger enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'voice_entry_ledger'
      and policyname = 'voice_entry_ledger_select_own'
  ) then
    create policy "voice_entry_ledger_select_own"
      on public.voice_entry_ledger for select
      using (auth.uid() = user_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'voice_entry_ledger'
      and policyname = 'voice_entry_ledger_insert_own'
  ) then
    create policy "voice_entry_ledger_insert_own"
      on public.voice_entry_ledger for insert
      with check (auth.uid() = user_id);
  end if;
end
$$;
